<footer class="about">
    <h2>Acknowledgement of Country</h2>
    <div class="footerLink">
        <div style="margin-right: 20px;">
            <img class= "flag" src="Images/australian-aboriginal-flag.png" alt="Australian aboriginal Flag">
        </div>
        <div style="margin-right: 50px;">
            <img class= "flag" src="Images/torres-strait-islands-flag.png" alt="Torres Strait islands Flag">
        </div>
        <div>
            <p>We acknowledges the Traditional Owners of Country throughout Australia and acknowledges their continuing connection to land, waters and community. We pay our respects to the people, the cultures and the Elders past and present.</p>
            
        </div>
    </div>
    <div class="footer-left">
    <a href="https://105676558cos10026.atlassian.net/jira/software/projects/DEV/boards/1">Jira Project</a>
    <span>›</span>
    <a href="https://github.com/JakeStahlUNI/COS10026_WebTech_TeamProject">GitHub Repository</a>
    <span>›</span>
    <a href="mailto:info@pixelcraft.com">Contact us at info@pixelcraft.com</a>
    <p>&copy; 2026 PixelCraft. All rights reserved.</p>
    </div>
</footer>