<footer class="footer">
  <div class="footer-left">
    <a href="https://105676558cos10026.atlassian.net/jira/software/projects/DEV/boards/1">Jira Project</a>
    <span>›</span>
    <a href="https://github.com/JakeStahlUNI/COS10026_WebTech_TeamProject">GitHub Repository</a>
    <span>›</span>
    <a href="mailto:info@pixelcraft.com">Contact us at info@pixelcraft.com</a>
  </div>
    <div class="footer-right">
        <p>&copy; <?php echo date("Y"); ?> PixelCraft Agency. All rights reserved.</p>
    </div>
</footer>