
<header class="header">
  <a href="index.php" class="logo-link">
    <img src="images/Logo.png" alt="PixelCraft" class="logo">
  </a>

  <div class="search-and-nav">
    <nav class="nav-links">
      <a href="about.php">About</a>
      <a href="Jobs.php">Jobs</a>
      <a href="Apply.php">Apply</a>
    </nav>
    <div class="search-bar">
      <input type="text" placeholder="Search..">
      <button type="submit">Search</button>
    </div>
  </div>
</header>